Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
test_vehicle = trainer.train(df, config)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nrel/routee/powertrain/trainers/smartcore_random_forest.py:17[0m, in [0;36mSmartcoreRandomForestTrainer.inner_train[0;34m(self, features, target, config)[0m
[1;32m     16[0m [38;5;28;01mtry[39;00m:
[0;32m---> 17[0m     [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mpowertrain_rust[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m RustRandomForest
[1;32m     18[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

[0;31mModuleNotFoundError[0m: No module named 'powertrain_rust'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[10], line 1[0m
[0;32m----> 1[0m test_vehicle [38;5;241m=[39m [43mtrainer[49m[38;5;241;43m.[39;49m[43mtrain[49m[43m([49m[43mdf[49m[43m,[49m[43m [49m[43mconfig[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nrel/routee/powertrain/trainers/trainer.py:56[0m, in [0;36mTrainer.train[0;34m(self, data, config)[0m
[1;32m     54[0m         name_list[38;5;241m.[39mappend(distance_name)
[1;32m     55[0m     sub_features [38;5;241m=[39m all_features[name_list]
[0;32m---> 56[0m     estimator [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43minner_train[49m[43m([49m
[1;32m     57[0m [43m        [49m[43mfeatures[49m[38;5;241;43m=[39;49m[43msub_features[49m[43m,[49m[43m [49m[43mtarget[49m[38;5;241;43m=[39;49m[43mtarget[49m[43m,[49m[43m [49m[43mconfig[49m[38;5;241;43m=[39;49m[43mconfig[49m
[1;32m     58[0m [43m    [49m[43m)[49m
[1;32m     59[0m     estimators[feature_set[38;5;241m.[39mfeatures_id] [38;5;241m=[39m estimator
[1;32m     61[0m metadata [38;5;241m=[39m Metadata(config[38;5;241m=[39mconfig)

File [0;32m/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/nrel/routee/powertrain/trainers/smartcore_random_forest.py:19[0m, in [0;36mSmartcoreRandomForestTrainer.inner_train[0;34m(self, features, target, config)[0m
[1;32m     17[0m     [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mpowertrain_rust[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m RustRandomForest
[1;32m     18[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[0;32m---> 19[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     20[0m         [38;5;124m"[39m[38;5;124mPlease install powertrain_rust to use [39m[38;5;124m"[39m
[1;32m     21[0m         [38;5;124m"[39m[38;5;124mthe SmartCoreRandomForest estimator.[39m[38;5;124m"[39m
[1;32m     22[0m     )
[1;32m     24[0m x [38;5;241m=[39m features[38;5;241m.[39mvalues[38;5;241m.[39mtolist()
[1;32m     25[0m y [38;5;241m=[39m target[38;5;241m.[39mvalues

[0;31mImportError[0m: Please install powertrain_rust to use the SmartCoreRandomForest estimator.

